### ISSUE TITLE
Requires pyquery ?

### ISSUE THREAD

**Issue by kemege** [jackyyf/paste.py#9]
It looks like the script requires `pyquery`, which requires `cssselect` and `lxml` and it's not listed in the "Dependency" part of README :)

**Comment by jackyyf** [comment]
Em.. I think I should point out that with dependency, pyquery requires cssselect and lxml, and with `pip install pyquery`, they will installed automaticly. Since dependency handling is not my job (maybe author or maintainers of pypi?), I will mark this issue as invalid. 

And more, nothing was depending on pyquery **NOW** (at some very early version of ubuntupaste, it actually depends on pyquery, but since lxml strips all newlines, I've implemented a simple html tag filter.) Maybe I'll change README to exclude pyquery from dependency :)
